spring:
  data:
    mongodb:
      uri: ${DATABASE_URL}
    redis:
      url: ${REDIS_URL}
cors:
  allowed-origins: ""
  allowed-methods: ""
  allowed-headers: ""
  exposed-headers: ""
management:
  endpoints:
    web:
      exposure:
        include: "health"
