spring:
  data:
    mongodb:
      uri: "mongodb://root:letmein@localhost:27017/serviceDB?authSource=admin"
    redis:
      url: "redis://localhost:6379"
  graphql:
    graphiql:
      enabled: true
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

logging:
  file:
    name: Application.log

