spring:
  profiles:
    active: @spring.profiles.active@
  data:
    mongodb:
      auto-index-creation: true
  cache:
    type: redis
  config:
    import: optional:secrets.yml
application:
  title: Service API
  version: 1.0
info:
  app:
    name: ${application.title}
    description: Service API
    version: ${application.version}
    title: ${application.title}
    author: Ali Alaei
    docs: https://aalaei.github.io/spring-boot-service-task/javadoc/
    apiDocs: /swagger-ui.html
    repo: https://github.com/aalaei/spring-boot-service-task
management:
  info:
    env:
      enabled: true